DROP TABLE IF EXISTS skins;
--##SPLITTER##--
DROP TABLE IF EXISTS users;
--##SPLITTER##--
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT, 
    username VARCHAR(25) NOT NULL,
    country TEXT NOT NULL,
    comp_points INT DEFAULT 0 NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);
--##SPLITTER##--
CREATE TABLE skins (
    id INT NOT NULL AUTO_INCREMENT, 
    code CHAR(27) NOT NULL,
    skin_name VARCHAR(60) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    creator INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (creator) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);
